apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  labels:
    app: {name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {name}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
      - image: {image}
        name: mysql
        args: ["--default-authentication-plugin=mysql_native_password", "--skip-log-bin"]
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {name}-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {name}-secret
              key: MYSQL_USER
        - name: MYSQL_DATABASE
          value: {database}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {name}-secret
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: {name}-hostpath
          mountPath: /var/lib/mysql
      volumes:
      - name: {name}-hostpath
        hostPath:
          path: {hostpath}
          type: DirectoryOrCreate
