apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app: {deployment.name}
  name: {secret.name}
  annotations:
    helm.sh/hook: pre-install
data:
  MYSQL_PASSWORD: {base64.b64encode(''.join(random.choices(string.ascii_letters + string.digits, k=32).encode('ascii')))}
  MYSQL_ROOT_PASSWORD: {base64.b64encode(''.join(random.choices(string.ascii_letters + string.digits, k=32).encode('ascii')))}
  MYSQL_USER: {base64.b64encode(f'mysql-{release.name}-user')}
