apiVersion: v1
kind: Service
metadata:
  name: {service.name}
  labels:
    app: {deployment.name}
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
  selector:
    app: {deployment.name}
  type: ClusterIP